name: p2lantransfer
description: P2Lan Transfer - Make LAN transfers easy, no server needed.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.18
  file_picker: ^8.0.0+1
  cross_file: ^0.3.3+8
  path_provider: ^2.1.3
  intl: 0.20.2 
  shared_preferences: 2.2.2
  crypto: ^3.0.3
  http: ^1.2.1
  math_expressions: ^2.6.0
  flutter_localizations:
    sdk: flutter  
  flutter_gen: ^5.9.0
  logger: 2.5.0
  logging: ^1.2.0
  quick_actions: ^1.1.0
  window_manager: ^0.5.0
  flutter_colorpicker: ^1.1.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.4
  # P2P Data Transfer dependencies
  connectivity_plus: ^6.0.5
  network_info_plus: ^5.0.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  multicast_dns: ^0.3.2+6
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  cryptography: ^2.7.0
  uuid: ^4.4.0
  nsd: ^4.0.3
  # workmanager: ^0.5.1  # Temporarily disabled due to Flutter compatibility issues
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  open_file: ^3.3.2
  share_plus: ^11.0.0
  path: ^1.8.3
  flutter_local_notifications: ^17.2.3
  workmanager: 0.7.0
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  get: ^4.7.2

  # Desktop drag & drop support
  desktop_drop: ^0.4.0

  # Clipboard management
  clipboard: ^2.0.2
  pasteboard: ^0.4.0

  # Archive/compression support
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # hive_generator: ^2.0.1  # Commented out - migrated to Isar
  isar_generator: 3.1.0+1
  build_runner: ^2.4.12
  # Timeline viewer
  timelines_plus: ^1.0.7
  remove_unused_localizations: ^1.0.1

flutter:
  uses-material-design: true
  generate: true
  # platforms:
  #   windows:
  #     pluginClass: DesktopDropPlugin
  assets:
    - assets/
    - assets/func_info/